"""Initial Migration

Revision ID: 4a8f23480c78
Revises: d310301141ef
Create Date: 2021-06-12 22:48:14.942144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8f23480c78'
down_revision = 'd310301141ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_title', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_category', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('pitch_comment', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_category_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'content')
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_category_id_fkey', 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'dislikes')
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'pitch_comment')
    op.drop_column('pitches', 'pitch_category')
    op.drop_column('pitches', 'pitch_title')
    op.drop_column('pitches', 'pitch_id')
    # ### end Alembic commands ###
